[package]
name = "bolt_ts_config"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
paste = { workspace = true }
